# Generated by Django 4.0 on 2021-12-31 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('amount', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='counted')),
                ('counted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('counted', 'Counted')], default='counted', max_length=10)),
            ],
        ),
    ]
