# Generated by Django 4.0 on 2022-01-26 21:12

import counteye.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='conf/default.jpg', upload_to=counteye.models.upload, verbose_name='Image')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='counteye.category')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('image', models.ImageField(default='count/default.jpg', upload_to=counteye.models.upload_to, verbose_name='Image')),
                ('description', models.TextField(null=True)),
                ('amount', models.CharField(max_length=251)),
                ('slug', models.SlugField(max_length=250, unique_for_date='counted')),
                ('counted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('counted', 'Counted')], default='counted', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.newuser')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='counteye.category')),
            ],
        ),
    ]
