# Generated by Django 4.0 on 2022-01-26 22:53

import counteye.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counteye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionmodel',
            name='image',
            field=models.ImageField(default='n/default.jpg', upload_to=counteye.models.upload, verbose_name='Image'),
        ),
    ]
