# Generated by Django 4.0 on 2022-02-12 02:18

import counteye.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counteye', '0002_alter_detectionmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detectionmodel',
            name='image',
            field=models.ImageField(default='conf/p/default.jpg', upload_to=counteye.models.upload, verbose_name='Image'),
        ),
    ]
