# Generated by Django 4.0 on 2022-02-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('counteye', '0003_change_count_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.newuser'),
        ),
        migrations.AlterField(
            model_name='count',
            name='product',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
