# Generated by Django 4.0 on 2022-02-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counteye', '0004_alter_count_amount_alter_count_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='description',
        ),
        migrations.CreateModel(
            name='ProductsRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='counteye.category')),
            ],
        ),
    ]
