# Generated by Django 4.0 on 2022-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counteye', '0005_remove_count_description_productsregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='slug',
        ),
    ]
