# Generated by Django 4.0 on 2022-02-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counteye', '0006_remove_count_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsregister',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DetectionModel',
        ),
    ]
